[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  BUN_VERSION = "1.2.18"

# Netlify Edge Functions 配置
[functions]
  directory = "netlify/functions"

# Next.js 静态资源处理 - 确保正确的 MIME 类型
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  headers = {Cache-Control = "public, max-age=31536000, immutable"}

# Next.js 图片优化
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image/:splat"
  status = 200

# API 路由处理
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# SPA 回退（必须在最后）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 静态资源缓存头
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 字体文件缓存
[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS 文件 MIME 类型
[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# JS 文件 MIME 类型
[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# 字体文件 MIME 类型
[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000, immutable"

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Netlify 特定配置
[context.production.environment]
  NETLIFY = "true"

[context.deploy-preview.environment]
  NETLIFY = "true"

[context.branch-deploy.environment]
  NETLIFY = "true"
